name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy frontend to S3
    runs-on: ubuntu-latest

    env:
      BUCKET_NAME: whatjacketdoineed.com
      DISTRIBUTION_ID: ERL2RXC8LK2ZT
      REGION: us-east-1
      LAMBDA_FUNCTION_NAME: jacket-recommender

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Sync frontend files to S3
        run: |
          aws s3 sync terraform/frontend/ s3://${{ env.BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Zip Lambda
        run: |
          cd terraform/lambda
          zip -r ../../lambda_function_payload.zip handler.py
          cd ../..

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://lambda_function_payload.zip
